// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dquifceoxxcttpmqnqww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxdWlmY2VveHhjdHRwbXFucXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzg3MDEsImV4cCI6MjA2ODc1NDcwMX0.GFMOzELcMrJifGB_5j5S4psmxn9ve1zXM5N0tZmPpVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});